// Typelizer digest f12787652b2a995512087dd13d9307a6
//
// DO NOT MODIFY: This file was automatically generated by `cargo loco task routes:generate` from src/route_table.rs.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /settings/sessions */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/settings/sessions', {}, options),
    method: 'get',
  }),
}
