//! Fails when the committed `frontend/routes/*.ts` differ from what `src/route_table.rs`
//! generates. Fix with `cargo loco task routes:generate` and commit the result.

use std::path::Path;

use inertia_rust_starter_kit::{route_table, tasks::routes_generate};

#[test]
fn committed_ts_routes_match_the_route_table() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join(route_table::TS_DIR);
    let expected = route_table::generate_ts();
    let mut problems = Vec::new();

    for (rel, contents) in &expected {
        match std::fs::read_to_string(dir.join(rel)) {
            Ok(actual) if actual == *contents => {}
            Ok(_) => problems.push(format!("{rel} is out of date")),
            Err(e) => problems.push(format!("{rel} is missing ({e})")),
        }
    }
    for path in routes_generate::ts_files(&dir).expect("read frontend/routes") {
        let rel = path
            .strip_prefix(&dir)
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        if rel != route_table::TS_RUNTIME && !expected.iter().any(|(f, _)| *f == rel) {
            problems.push(format!("{rel} is not generated by the route table (stale)"));
        }
    }

    assert!(
        problems.is_empty(),
        "frontend/routes is stale; run `cargo loco task routes:generate`:\n  {}",
        problems.join("\n  ")
    );
}

/// The frontend imports these names from `@/routes`; they are the Rails kit's Typelizer
/// exports and must not change.
#[test]
fn index_keeps_the_rails_kit_export_names() {
    let (_, index) = route_table::generate_ts()
        .into_iter()
        .find(|(f, _)| f == "index.ts")
        .unwrap();
    for name in [
        "Routes",
        "dashboard",
        "home",
        "identityEmailVerifications",
        "identityPasswordResets",
        "sessions",
        "settingsEmails",
        "settingsPasswords",
        "settingsProfiles",
        "settingsSessions",
        "users",
    ] {
        assert!(
            index.contains(&format!("export {{ default as {name} }}")),
            "{name}"
        );
    }
    for name in [
        "editIdentityPasswordReset",
        "identityEmailVerification",
        "identityPasswordReset",
        "newIdentityPasswordReset",
        "root",
        "session",
        "settingsAppearance",
        "settingsEmail",
        "settingsPassword",
        "settingsProfile",
        "signIn",
        "signUp",
    ] {
        assert!(index.contains(&format!("export const {name} = ")), "{name}");
    }
}
