//! The kit's scaffold templates (`.loco-templates/`) against Loco's real generator.
//!
//! Copies the files the generator reads and injects into (the app's `src/`, `migration/`,
//! `tests/`, `frontend/` and the templates) into a temp dir, runs `loco_gen::generate` for a
//! scaffold there the way `cargo loco generate scaffold` does (with the command line and
//! environment `src/generate.rs` plans), stands in for `cargo loco db entities` with the
//! entity it would write, then runs `scaffold:pages`. It asserts on what was written: every
//! injection anchor matched, the Rust half is wired and account-scoped (or global with
//! `--global`), and the pages exist.
//!
//! The resources are synthetic (`widgets`, `gadgets`, `gizmos`) so an app that grows a real
//! `posts` or `comments` doesn't collide with them.
//!
//! It does not compile the result: `tests/controller_generator.rs`'s `--ignored` build test
//! generates scaffolds in a full copy of the app and runs clippy, their request tests, `tsc` and
//! ESLint there. This test's job is to fail fast when a Loco upgrade (or an edit to
//! `src/app.rs`, `src/route_table.rs`, the models or the sidebar) moves an anchor the templates
//! rely on, or a template stops producing the scoped shape.
//!
//! Its own test binary, because Loco's generator resolves `.loco-templates/` against the process
//! working directory, which this test changes.

use std::path::{Path, PathBuf};

use inertia_rust_starter_kit::{generate, tasks::scaffold_pages};

/// Every top-level path the scaffold reads or writes.
const COPY: &[&str] = &[".loco-templates", "src", "migration", "tests", "frontend"];

fn copy_dir(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).unwrap();
    for entry in std::fs::read_dir(from).unwrap() {
        let entry = entry.unwrap();
        let target = to.join(entry.file_name());
        if entry.file_type().unwrap().is_dir() {
            if entry.file_name() != "node_modules" {
                copy_dir(&entry.path(), &target);
            }
        } else {
            std::fs::copy(entry.path(), target).unwrap();
        }
    }
}

/// The model skeleton `loco_rs::db::entities` writes next to a new entity.
fn model_skeleton(table: &str) -> String {
    let pascal = {
        let mut c = table.chars();
        c.next()
            .map(|f| f.to_ascii_uppercase().to_string() + c.as_str())
            .unwrap_or_default()
    };
    format!(
        r"use sea_orm::entity::prelude::*;
pub use super::_entities::{table}::{{ActiveModel, Model, Entity}};
pub type {pascal} = Entity;

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {{
    async fn before_save<C>(self, _db: &C, insert: bool) -> std::result::Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {{
        if !insert && self.updated_at.is_unchanged() {{
            let mut this = self;
            this.updated_at = sea_orm::ActiveValue::Set(chrono::Utc::now().into());
            Ok(this)
        }} else {{
            Ok(self)
        }}
    }}
}}

// implement your read-oriented logic here
impl Model {{}}

// implement your write-oriented logic here
impl ActiveModel {{}}

// implement your custom finders, selectors oriented logic here
impl Entity {{}}
"
    )
}

/// What `cargo loco db entities` writes (after `db migrate`) for a table with these field
/// lines, in the shape sea-orm-cli 2.0 generates (relations left out: the templates don't read
/// them).
fn entity(table: &str, fields: &str) -> String {
    format!(
        r#"//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{{Deserialize, Serialize}};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "{table}")]
pub struct Model {{
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
{fields}
}}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {{}}
"#
    )
}

/// `widgets name:string! body:text published:bool! views:int! rating:double published_on:date
/// archived_at:tstz` + the `account:references` the kit adds.
const WIDGETS_FIELDS: &str = "    pub name: String,
    #[sea_orm(column_type = \"Text\", nullable)]
    pub body: Option<String>,
    pub published: bool,
    pub views: i64,
    #[sea_orm(column_type = \"Double\", nullable)]
    pub rating: Option<f64>,
    pub published_on: Option<Date>,
    pub archived_at: Option<DateTimeWithTimeZone>,
    pub account_id: i64,";

/// `gadgets title:string! widget:references owner:references? creator:references` + account.
/// `owner`/`creator` have no table of their own (`users:references:creator_id` is the way to
/// say "a user"), so they are left out of the form with a note.
const GADGETS_FIELDS: &str = "    pub title: String,
    pub widget_id: i64,
    pub owner_id: Option<i64>,
    pub creator_id: i64,
    pub account_id: i64,";

/// `gizmos label:string! user:references --global`.
const GIZMOS_FIELDS: &str = "    pub label: String,
    pub user_id: i64,";

fn read(root: &Path, rel: &str) -> String {
    std::fs::read_to_string(root.join(rel)).unwrap_or_else(|e| panic!("{rel}: {e}"))
}

fn app_copy(name: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!("irsk-scaffold-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&root);
    let source = Path::new(env!("CARGO_MANIFEST_DIR"));
    for dir in COPY {
        copy_dir(&source.join(dir), &root.join(dir));
    }
    root
}

/// Run the generator for `line` (`generate scaffold …`) the way `cargo loco generate` does after
/// `src/generate.rs`: the planned command line, with the planned environment set.
fn scaffold(root: &Path, line: &str) -> Result<loco_gen::GenerateResults, loco_gen::Error> {
    let args: Vec<String> = std::iter::once("cli")
        .chain(line.split(' '))
        .map(str::to_owned)
        .collect();
    let plan = generate::plan(&args, root).unwrap().expect("a scaffold");
    for (key, value) in &plan.env {
        std::env::set_var(key, value);
    }
    let name = plan.args[3].clone();
    let fields = plan.args[4..]
        .iter()
        .map(|f| {
            let (n, t) = f.split_once(':').unwrap();
            (n.to_owned(), t.to_owned())
        })
        .collect();
    loco_gen::generate(
        &loco_gen::RRgen::with_working_dir(root),
        loco_gen::Component::Scaffold {
            name,
            with_tz: true,
            fields,
            frontend: false,
            auth: true,
        },
        &loco_gen::AppInfo {
            app_name: "inertia_rust_starter_kit".into(),
            working_dir: root.to_path_buf(),
        },
    )
}

/// Loco writes the entity and the model skeleton in `db entities`, before rendering the
/// scaffold templates.
fn write_entity(root: &Path, table: &str, fields: &str) {
    std::fs::write(
        root.join(format!("src/models/_entities/{table}.rs")),
        entity(table, fields),
    )
    .unwrap();
    std::fs::write(
        root.join(format!("src/models/{table}.rs")),
        model_skeleton(table),
    )
    .unwrap();
}

fn compact(s: &str) -> String {
    s.split_whitespace().collect()
}

#[test]
fn scaffold_templates_generate_a_wired_account_scoped_resource() {
    let root = app_copy("scoped");
    // The model generator shells out to `cargo loco db migrate/entities` unless told not to;
    // the entities are written by `write_entity` instead.
    std::env::set_var("SKIP_MIGRATION", "1");
    std::env::set_current_dir(&root).unwrap();

    // --- widgets: account-scoped by default, with a column the form can't edit -------------
    write_entity(&root, "widgets", WIDGETS_FIELDS);
    let results = scaffold(
        &root,
        "generate scaffold widgets name:string! body:text published:bool! views:int! \
         rating:double published_on:date archived_at:tstz",
    )
    .expect("the kit's scaffold templates render and every injection anchor matches");
    let messages = loco_gen::collect_messages(&results);
    for template in [
        "model/test.t",
        "scaffold/api/controller.t",
        "scaffold/api/dto.t",
    ] {
        assert!(
            messages.contains(&format!(".loco-templates/{template}")),
            "{template} was not picked up from .loco-templates:\n{messages}"
        );
    }
    assert!(messages.contains("under /{account_slug}"), "{messages}");
    assert!(
        messages.contains("Not in the form or the page props: archived_at"),
        "a tstz column is skipped with a note, not refused:\n{messages}"
    );

    let controller = read(&root, "src/controllers/widgets.rs");
    assert!(controller.contains("auth::CurrentAccount"));
    assert!(!controller.contains("Authenticated"), "{controller}");
    assert!(controller.contains("widgets::Model::list(&ctx.db, current.account.id)"));
    assert_eq!(
        controller
            .matches("widgets::Model::find_in_account(&ctx.db, current.account.id, id)")
            .count(),
        4,
        "show, edit, update and destroy all look the id up in the account"
    );
    assert!(controller.contains("widgets::Model::create(&ctx.db, current.account.id, &params)"));
    assert!(controller.contains("Redirect::to(route_table::widget_path(slug, widget.id))"));
    assert!(
        controller.contains("NoPrecognition"),
        "destroy refuses precognition"
    );
    assert!(read(&root, "src/controllers/mod.rs").contains("pub mod widgets;"));
    assert!(read(&root, "src/app.rs")
        .contains("AppRoutes::empty()\n            .add_route(controllers::widgets::routes())"));

    let table = read(&root, "src/route_table.rs");
    assert!(table.contains("pub const WIDGETS: &str = \"/{account_slug}/widgets\";\n"));
    assert!(table.contains("pub const WIDGET: &str = \"/{account_slug}/widgets/{id}\";\n"));
    assert!(table.contains("pub fn widgets_path(slug: &str) -> String"));
    assert!(table.contains("pub fn edit_widget_path(slug: &str, id: i64) -> String"));
    let flat = compact(&table);
    for route in [
        "index", "create", "new", "edit", "show", "update", "destroy",
    ] {
        assert!(
            flat.contains(&format!("route(\"widgets.{route}\"")),
            "widgets.{route}"
        );
    }
    assert!(
        table.find("pub const WIDGETS").unwrap() < table.find("// scaffold:paths").unwrap(),
        "paths go above the anchor so the next scaffold appends after them"
    );

    let model = read(&root, "src/models/widgets.rs");
    assert!(model.contains("pub struct WidgetParams {"));
    assert!(
        !model.contains("pub account_id: Option<String>"),
        "the account is never a param"
    );
    assert!(
        !model.contains("archived_at"),
        "a skipped column is not a param or a prop"
    );
    assert!(model.contains("cast::string(&mut errors, \"name\""));
    assert!(model.contains("cast::optional_number(&mut errors, \"rating\""));
    assert!(model.contains("cast::optional_date(&mut errors, \"published_on\""));
    assert!(model.contains("cast::boolean(&mut errors, \"published\""));
    assert!(model.contains("pub async fn list(db: &DatabaseConnection, account_id: i64)"));
    assert!(model.contains(
        "pub async fn find_in_account(db: &DatabaseConnection, account_id: i64, id: i64)"
    ));
    assert_eq!(
        model
            .matches(".filter(Column::AccountId.eq(account_id))")
            .count(),
        2
    );
    assert!(model.contains("account_id: sea_orm::ActiveValue::Set(account_id),"));
    assert!(
        !model.contains("fn find_by_id"),
        "no unscoped finder to call by mistake"
    );
    assert!(
        !model.contains("impl Model {}"),
        "the empty placeholders are replaced"
    );
    assert!(model.contains(".first(db)"), "finders use db::First");
    assert_eq!(model.matches("use loco_rs::model::").count(), 1);

    let test = read(&root, "tests/requests/widgets.rs");
    assert!(
        test.contains("json!({ \"name\": [\"can't be blank\"], \"views\": [\"can't be blank\"] })")
    );
    assert!(test.contains("async fn another_accounts_widgets_are_not_found()"));
    assert!(
        test.contains("assert_eq!(created.account_id, ACME, \"the account comes from the URL\");")
    );
    assert!(test.contains("&route_table::widgets_path(\"acme\")"));
    assert!(read(&root, "tests/requests/mod.rs").contains("mod widgets;"));
    assert!(read(&root, "tests/models/widgets.rs").contains("async fn can_query_widgets()"));

    let generated = scaffold_pages::generate(&root, "widgets").unwrap();
    for page in ["index", "show", "new", "edit", "form"] {
        let rel = format!("frontend/pages/widgets/{page}.tsx");
        assert!(
            generated.written.contains(&rel),
            "{rel} not written: {generated:?}"
        );
    }
    assert_eq!(
        generated.skipped,
        ["archived_at (DateTimeWithTimeZone: no form input)"]
    );
    let form = read(&root, "frontend/pages/widgets/form.tsx");
    assert!(form.contains("export interface Widget {"));
    assert!(form.contains("rating: number | null"));
    assert!(
        !form.contains("account_id") && !form.contains("archived_at"),
        "{form}"
    );
    assert!(form.contains("<Checkbox"));
    assert!(form.contains("type=\"date\""));
    let index = read(&root, "frontend/pages/widgets/index.tsx");
    assert!(
        index.contains("const { slug: accountSlug } = useCurrentAccount()"),
        "{index}"
    );
    assert!(
        index.contains("routes.show({ accountSlug, id: widget.id })"),
        "{index}"
    );
    assert!(index.contains("routes.new(accountSlug)"), "{index}");
    let show = read(&root, "frontend/pages/widgets/show.tsx");
    assert!(
        show.contains("const at = { accountSlug, id: widget.id }"),
        "{show}"
    );
    assert!(show.contains("routes.destroy(at)"));
    assert!(read(&root, "frontend/pages/widgets/new.tsx").contains("routes.create(accountSlug)"));
    assert!(read(&root, "frontend/pages/widgets/edit.tsx").contains("action={routes.update(at)}"));
    for page in ["index", "show", "new", "edit", "form"] {
        let src = read(&root, &format!("frontend/pages/widgets/{page}.tsx"));
        assert!(
            !src.contains("{{") && !src.contains("{%"),
            "no unrendered Tera in {page}"
        );
    }
    let sidebar = read(&root, scaffold_pages::SIDEBAR);
    assert!(
        sidebar.contains("href: widgets.index(account.slug).url, icon: NotebookText },\n        // scaffold:nav\n")
            || compact(&sidebar).contains(&compact("href: widgets.index(account.slug).url, icon: NotebookText }, // scaffold:nav\n")),
        "the link is in the account's nav:\n{sidebar}"
    );
    assert!(
        scaffold_pages::generate(&root, "widgets")
            .unwrap()
            .written
            .is_empty(),
        "a second run overwrites nothing"
    );

    // --- gadgets: belongs to a widget, which belongs to the account too -------------------
    write_entity(&root, "gadgets", GADGETS_FIELDS);
    let results = scaffold(
        &root,
        "generate scaffold gadgets title:string! widget:references owner:references? creator:references",
    )
    .expect("a second scaffold");
    let messages = loco_gen::collect_messages(&results);
    assert!(
        messages.contains("owner_id (no `owners` table to pick from)")
            && messages.contains(
                "creator_id (no `creators` table to pick from; required, so set it in `create`)"
            ),
        "{messages}"
    );
    let table = read(&root, "src/route_table.rs");
    assert!(table.find("pub const WIDGETS").unwrap() < table.find("pub const GADGETS").unwrap());

    // `belongs_to :widget`, within the account: a widget of another account "must exist" not.
    let gadgets = read(&root, "src/models/gadgets.rs");
    assert!(gadgets.contains(
        "item.widget_id = sea_orm::ActiveValue::Set(cast::reference(&mut errors, \"widget\", self.widget_id.as_deref()));"
    ), "{gadgets}");
    assert!(compact(&gadgets).contains(&compact(
        "super::_entities::widgets::Entity::find_by_id(id).filter(super::_entities::widgets::Column::AccountId.eq(*item.account_id.as_ref()))"
    )), "{gadgets}");
    assert!(gadgets.contains("errors.add(\"widget\", \"must exist\");"));
    assert!(
        !gadgets.contains("owner") && !gadgets.contains("creator"),
        "skipped references:\n{gadgets}"
    );
    assert!(
        gadgets.contains("pub async fn widget_options(db: &DatabaseConnection, account_id: i64)")
    );
    assert!(
        gadgets.contains(".filter(super::_entities::widgets::Column::AccountId.eq(account_id))")
    );
    let gadgets_controller = read(&root, "src/controllers/gadgets.rs");
    assert!(gadgets_controller.contains(
        "\"widget_options\": gadgets::Model::widget_options(&ctx.db, account_id).await?,"
    ));
    assert!(gadgets_controller.contains("form_options(&ctx, current.account.id).await?"));
    let gadgets_test = read(&root, "tests/requests/gadgets.rs");
    assert!(gadgets_test
        .contains("async fn create_parents(ctx: &AppContext, account_id: i64, ids: &[i64])"));
    assert!(gadgets_test.contains("row.account_id = sea_orm::ActiveValue::Set(account_id);"));
    assert!(gadgets_test
        .contains("async fn a_parent_from_another_account_is_not_offered_and_does_not_exist()"));
    assert!(gadgets_test
        .contains("json!({ \"title\": [\"can't be blank\"], \"widget\": [\"must exist\"] })"));
    assert!(
        !test.contains("create_parents"),
        "a resource without references gets none"
    );

    let generated = scaffold_pages::generate(&root, "gadgets").unwrap();
    assert!(generated
        .written
        .contains(&"frontend/pages/gadgets/form.tsx".to_string()));
    assert_eq!(
        generated.skipped,
        [
            "owner_id (no `owners` table to pick from)",
            "creator_id (no `creators` table to pick from)"
        ]
    );
    let form = read(&root, "frontend/pages/gadgets/form.tsx");
    assert!(form.contains("from \"@/components/ui/select\""), "{form}");
    assert!(form.contains("<Select\n                name=\"widget_id\""));
    assert!(form.contains("widgetOptions.map((option) => ("));
    assert!(
        form.contains("errors={errors.widget?.map("),
        "errors are keyed by association"
    );
    assert!(
        !form.contains("owner") && !form.contains("creator"),
        "{form}"
    );
    let new_page = read(&root, "frontend/pages/gadgets/new.tsx");
    assert!(
        new_page.contains("widget_options: SelectOption[]"),
        "{new_page}"
    );
    assert!(new_page.contains("widgetOptions={widget_options}"));

    // --- gizmos: `--global` is the plain signed-in resource ---------------------------------
    write_entity(&root, "gizmos", GIZMOS_FIELDS);
    let results = scaffold(
        &root,
        "generate scaffold gizmos label:string! user:references --global",
    )
    .expect("a global scaffold");
    assert!(loco_gen::collect_messages(&results).contains("global: no account scope"));
    let gizmos = read(&root, "src/controllers/gizmos.rs");
    assert!(gizmos.contains("auth::Authenticated"));
    assert!(!gizmos.contains("CurrentAccount"));
    assert!(gizmos.contains("gizmos::Model::find_by_id(&ctx.db, id)"));
    let table = read(&root, "src/route_table.rs");
    assert!(table.contains("pub const GIZMOS: &str = \"/gizmos\";\n"));
    assert!(table.contains("pub fn gizmo_path(id: i64) -> String"));
    let model = read(&root, "src/models/gizmos.rs");
    assert!(model.contains("pub async fn find_by_id(db: &DatabaseConnection, id: i64)"));
    assert!(!model.contains("account_id"));
    let generated = scaffold_pages::generate(&root, "gizmos").unwrap();
    assert!(generated.skipped.is_empty());
    let index = read(&root, "frontend/pages/gizmos/index.tsx");
    assert!(!index.contains("accountSlug"), "{index}");
    assert!(index.contains("routes.show(gizmo.id)"));
    let sidebar = read(&root, scaffold_pages::SIDEBAR);
    assert!(
        compact(&sidebar).contains(&compact(
            "href: gizmos.index().url, icon: NotebookText }, // scaffold:nav-global"
        )),
        "{sidebar}"
    );

    // The mailer generator sends from `settings.mail_from`, not Loco's built-in sender.
    loco_gen::generate(
        &loco_gen::RRgen::with_working_dir(&root),
        loco_gen::Component::Mailer {
            name: "project_mailer".into(),
        },
        &loco_gen::AppInfo {
            app_name: "inertia_rust_starter_kit".into(),
            working_dir: root.clone(),
        },
    )
    .expect("the mailer template renders");
    let mailer = read(&root, "src/mailers/project_mailer.rs");
    assert!(
        mailer.contains("from: Some(settings(ctx)?.mail_from.clone()),"),
        "{mailer}"
    );
    assert!(read(&root, "src/mailers/mod.rs").contains("pub mod project_mailer;"));

    std::env::set_current_dir(env!("CARGO_MANIFEST_DIR")).unwrap();
    std::fs::remove_dir_all(&root).unwrap();
}
