//! Fails when the committed `frontend/types/generated/*.ts` differ from what the props structs
//! in `src/page_types.rs` generate. Fix with `cargo loco task types:generate` and commit the
//! result.

use std::path::Path;

use inertia_rust_starter_kit::{page_types, tasks::routes_generate};

#[test]
fn committed_ts_types_match_the_props_structs() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join(page_types::TS_DIR);
    let expected = page_types::generate_ts();
    let mut problems = Vec::new();

    for (name, contents) in &expected {
        match std::fs::read_to_string(dir.join(name)) {
            Ok(actual) if actual == *contents => {}
            Ok(_) => problems.push(format!("{name} is out of date")),
            Err(e) => problems.push(format!("{name} is missing ({e})")),
        }
    }
    for path in routes_generate::ts_files(&dir).unwrap_or_default() {
        let name = path
            .strip_prefix(&dir)
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        if !expected.iter().any(|(f, _)| *f == name) {
            problems.push(format!(
                "{name} is not generated by any props struct (stale)"
            ));
        }
    }

    assert!(
        problems.is_empty(),
        "frontend/types/generated is stale; run `cargo loco task types:generate`:\n  {}",
        problems.join("\n  ")
    );
}
