//! The invitation delivery job. Generated by `cargo loco generate worker invitation_delivery`,
//! then written by hand.

use inertia_rust_starter_kit::{
    app::App,
    models::invitations,
    workers::invitation_delivery::{Worker, WorkerArgs},
};
use loco_rs::{app::AppContext, bgworker::BackgroundWorker, testing::prelude::*};
use sea_orm::EntityTrait;
use serial_test::serial;

async fn boot() -> AppContext {
    let boot = boot_test::<App>().await.unwrap();
    seed::<App>(&boot.app_context).await.unwrap();
    boot.app_context
}

fn deliveries(ctx: &AppContext) -> Vec<String> {
    ctx.mailer.as_ref().unwrap().deliveries().messages
}

async fn seeded(ctx: &AppContext) -> invitations::Model {
    invitations::Entity::find_by_id(1)
        .one(&ctx.db)
        .await
        .unwrap()
        .unwrap()
}

/// The job mints a new token, stores only its digest and mails the plain one: the link that
/// was valid before (the seed's) stops working.
#[tokio::test]
#[serial]
async fn it_mails_a_fresh_token_and_stores_only_its_digest() {
    let ctx = boot().await;
    let before = seeded(&ctx).await;
    Worker::build(&ctx)
        .perform(WorkerArgs { invitation_id: 1 })
        .await
        .unwrap();
    let mails = deliveries(&ctx);
    assert_eq!(mails.len(), 1);
    assert!(mails[0].contains("To: three@example.com"));
    let after = seeded(&ctx).await;
    assert_ne!(after.token_digest, before.token_digest);
    assert!(!mails[0].contains(&after.token_digest));
    assert!(
        invitations::Model::find_by_token(&ctx.db, invitations::SEED_TOKEN)
            .await
            .is_err()
    );
}

/// A revoked (deleted) invitation is skipped, not retried forever.
#[tokio::test]
#[serial]
async fn a_revoked_invitation_is_skipped() {
    let ctx = boot().await;
    seeded(&ctx).await.revoke(&ctx.db).await.unwrap();
    Worker::build(&ctx)
        .perform(WorkerArgs { invitation_id: 1 })
        .await
        .unwrap();
    assert!(deliveries(&ctx).is_empty());
}
