//! The `UserMailer` delivery job (`deliver_later`). Generated by
//! `cargo loco generate worker user_mailer_delivery`, then written by hand.

use inertia_rust_starter_kit::{
    models::{tokens::Purpose, users},
    route_table,
    workers::user_mailer_delivery::{Worker, WorkerArgs},
};
use loco_rs::bgworker::BackgroundWorker;
use serial_test::serial;

use crate::requests::{
    deliveries, settings, sid_from_mail, travel, user, with_app, with_app_config, ONE, PASSWORD,
};

/// Review #15: like `deliver_later`, only the user and the message are queued; the link is
/// minted when the job runs, so a queue delayed past the 20-minute lifetime still delivers a
/// working link, with the address the user has at delivery time.
#[tokio::test]
#[serial]
async fn queued_mail_carries_only_the_user_and_purpose_and_mints_the_token_on_delivery() {
    use loco_rs::config::WorkerMode;
    use sea_orm::{ConnectionTrait, Database, DbBackend, Statement};

    with_app_config(
        |config| config.workers.mode = WorkerMode::BackgroundQueue,
        |server, ctx| async move {
            let queue = ctx
                .queue_provider
                .clone()
                .expect("a queue in BackgroundQueue mode");
            queue.clear().await.unwrap();
            server
                .post(route_table::IDENTITY_PASSWORD_RESET)
                .json(&serde_json::json!({ "email": ONE }))
                .await;
            // Nothing is sent at request time; the job holds no token, URL or address.
            assert!(deliveries(&ctx).is_empty());
            let loco_rs::config::QueueConfig::Sqlite(qcfg) = ctx.config.queue.clone().unwrap()
            else {
                panic!("the test queue is SQLite");
            };
            let rows = Database::connect(&qcfg.uri)
                .await
                .unwrap()
                .query_all_raw(Statement::from_string(
                    DbBackend::Sqlite,
                    "SELECT name, task_data FROM sqlt_loco_queue WHERE status = 'queued'",
                ))
                .await
                .unwrap();
            assert_eq!(rows.len(), 1);
            let name: String = rows[0].try_get("", "name").unwrap();
            let data: String = rows[0].try_get("", "task_data").unwrap();
            assert_eq!(name, "UserMailerWorker");
            let one = user(&ctx, ONE).await;
            assert_eq!(
                serde_json::from_str::<serde_json::Value>(&data).unwrap(),
                serde_json::json!({ "user_id": one.id, "purpose": "password_reset" })
            );
            queue.clear().await.unwrap();

            // The worker picks it up 30 minutes later, after the user changed address.
            travel(&ctx, chrono::Duration::minutes(30));
            one.clone()
                .change_email(&ctx.db, Some("later@example.com"), PASSWORD)
                .await
                .unwrap();
            let args: WorkerArgs = serde_json::from_str(&data).unwrap();
            Worker::build(&ctx).perform(args).await.unwrap();
            let mails = deliveries(&ctx);
            assert_eq!(mails.len(), 1);
            assert!(mails[0].contains("To: later@example.com"), "{}", mails[0]);
            let found = users::Model::find_by_token_for(
                &ctx.db,
                Purpose::PasswordReset,
                &sid_from_mail(&mails[0]),
                settings(&ctx).secret_key_base.as_bytes(),
                &*inertia_rust_starter_kit::controllers::clock(&ctx),
            )
            .await
            .expect("the link is valid when delivered");
            assert_eq!(found.id, one.id);
        },
    )
    .await;
}

/// A job for a user deleted before delivery is dropped, not retried forever.
#[tokio::test]
#[serial]
async fn a_queued_mail_for_a_deleted_user_is_skipped() {
    with_app(|_server, ctx| async move {
        let one = user(&ctx, ONE).await;
        one.clone()
            .destroy_with_challenge(&ctx.db, PASSWORD)
            .await
            .unwrap();
        Worker::build(&ctx)
            .perform(WorkerArgs {
                user_id: one.id,
                purpose: Purpose::EmailVerification,
            })
            .await
            .unwrap();
        assert!(deliveries(&ctx).is_empty());
    })
    .await;
}
