{#- The request test for the kit's `cargo loco generate controller` (replaces Loco's JSON one).
    Pages render their component for a member; write actions redirect back (with Precognition
    refused); a signed-out visitor goes to sign in; a non-member of the account gets 404.
    Keep the names in step with controller.t. -#}
{%- set scoped = get_env(name="KIT_GENERATE_SCOPE", default="account") != "global" -%}
{%- set parent = get_env(name="KIT_GENERATE_PARENT", default="") -%}
{%- set nested = parent != "" -%}
{%- set writes = ["create", "update", "destroy"] -%}
{%- if nested -%}
{%- set child = name | split(pat="/") | last | snake_case -%}
{%- set parent_singular = get_env(name="KIT_GENERATE_PARENT_SINGULAR") -%}
{%- set child_singular = get_env(name="KIT_GENERATE_CHILD_SINGULAR") -%}
{%- set parent_scoped = scoped and get_env(name="KIT_GENERATE_PARENT_SCOPED", default="") == "1" -%}
{%- set test_name = parent ~ "_" ~ child -%}
{%- set parent_pascal = parent | pascal_case -%}
{%- set child_pascal = child | pascal_case -%}
{%- set pascal = parent_pascal ~ "::" ~ child_pascal -%}
{%- set helper = parent_singular ~ "_" ~ child_singular ~ "_path" -%}
{%- set parent_label = parent_singular | replace(from="_", to=" ") -%}
{%- else -%}
{%- set file_name = name | snake_case -%}
{%- set singular = get_env(name="KIT_GENERATE_SINGULAR", default=file_name) -%}
{%- set test_name = file_name -%}
{%- set pascal = file_name | pascal_case -%}
{%- set upper = file_name | upper_case -%}
{%- endif -%}
{#- The same pages, `show:<param>` and write actions as controller.t (which rejects bad input). -#}
{%- set_global pages = [] -%}
{%- set_global reads = false -%}
{%- set_global show_param = "" -%}
{%- set_global show_glob = false -%}
{%- set_global actions_written = [] -%}
{%- for action in actions -%}
{%- set parts = action.name | split(pat=":") -%}
{%- if parts | length > 1 -%}
{%- set raw = parts | last -%}
{%- set_global show_glob = raw is starting_with("*") -%}
{%- set_global show_param = raw | trim_start_matches(pat="*") -%}
{%- set_global reads = true -%}
{%- elif action.name in writes -%}
{%- if action.name not in actions_written %}{% set_global actions_written = actions_written | concat(with=action.name) %}{% endif -%}
{%- elif not nested -%}
{%- set_global reads = true -%}
{%- if action.name != "index" and action.name not in pages %}{% set_global pages = pages | concat(with=action.name) %}{% endif -%}
{%- endif -%}
{%- endfor -%}
{%- if not nested and (reads or actions_written | length == 0) %}{% set_global pages = ["index"] | concat(with=pages) %}{% endif -%}
{%- set has_show = show_param != "" -%}
{%- set collection = "index" in pages or "create" in actions_written -%}
{%- if has_show and (show_param != "id" or show_glob) %}{% set sample = `"a/b c"` %}{% if not show_glob %}{% set sample = `"a-b"` %}{% endif %}{% else %}{% set sample = "1" %}{% endif -%}
to: tests/requests/{{ test_name }}.rs
skip_exists: true
message: "Request test for `{{ pascal }}Controller` (tests/requests/{{ test_name }}.rs) was added. Run `cargo test --test mod requests::{{ test_name }}`."
injections:
- into: tests/requests/mod.rs
  after_last: "^mod \\w+;"
  content: "mod {{ test_name }};"
---
//! `{{ pascal }}Controller`. Generated by `cargo loco generate controller`; assert on the props and
//! the writes once the actions have them.{% if nested and parent_scoped %} The {{ parent | replace(from="_", to=" ") }} here are made by the test
//! itself (`{{ parent }}::ActiveModel::default_values()` in the seeds' accounts).{% endif %}

use {{ pkg_name }}::{% if nested and parent_scoped %}{models::_entities::{{ parent }}, route_table}{% else %}route_table{% endif %};
{%- if nested and parent_scoped %}
use sea_orm::ActiveModelTrait;
{%- endif %}
{%- if actions_written | length > 0 %}
use serde_json::json;
{%- endif %}
use serial_test::serial;

use super::*;
{%- if nested %}
{%- if parent_scoped %}

/// A {{ parent_label }} in the seeds' account `account_id` (Acme is 1, Globex 2); every other column is
/// its type's default. Set any other required column here.
async fn create_{{ parent_singular }}(ctx: &AppContext, account_id: i64) -> i64 {
    let mut row = {{ parent }}::ActiveModel::default_values();
    row.account_id = sea_orm::ActiveValue::Set(account_id);
    row.insert(&ctx.db).await.expect("insert a {{ parent_label }} for the test").id
}
{%- endif %}
{%- if scoped %}{% set at = "&route_table::" ~ helper ~ `("acme", ` ~ parent_singular ~ ")" %}{% else %}{% set at = "&route_table::" ~ helper ~ "(" ~ parent_singular ~ ")" %}{% endif %}

#[tokio::test]
#[serial]
async fn signed_out_visitors_are_sent_to_sign_in() {
    with_app(|server, _ctx| async move {
        let {{ parent_singular }} = 1;
{%- for action in actions_written %}
{%- if action == "create" %}{% set m = "post" %}{% elif action == "update" %}{% set m = "patch" %}{% else %}{% set m = "delete" %}{% endif %}
        assert_redirect(&server.{{ m }}({{ at }}).await, route_table::SIGN_IN);
{%- endfor %}
    })
    .await;
}

#[tokio::test]
#[serial]
async fn each_action_redirects_back_and_refuses_precognition() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
{%- if parent_scoped %}
        let {{ parent_singular }} = create_{{ parent_singular }}(&ctx, 1).await;
{%- else %}
        let {{ parent_singular }} = 1;
{%- endif %}
{%- for action in actions_written %}
{%- if action == "create" %}{% set m = "post" %}{% elif action == "update" %}{% set m = "patch" %}{% else %}{% set m = "delete" %}{% endif %}
        let res = server
            .{{ m }}({{ at }})
            .add_header("host", "localhost")
            .add_header("referer", "http://localhost/back-here")
            .json(&json!({}))
            .await;
        assert_redirect(&res, "/back-here");
        let res = server
            .{{ m }}({{ at }})
            .add_header("precognition", "true")
            .json(&json!({}))
            .await;
        assert_eq!(res.status_code(), 400, "{{ action }} refuses precognition");
{%- endfor %}
    })
    .await;
}
{%- if scoped %}

/// Members only: another account's URL is a 404{% if parent_scoped %}, and so is another account's
/// {{ parent_label }} through your own account's URL{% endif %}.
#[tokio::test]
#[serial]
async fn other_accounts_are_not_found() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await; // in Acme only
{%- if parent_scoped %}
        let theirs = create_{{ parent_singular }}(&ctx, 2).await;
{%- else %}
        let theirs = 1;
{%- endif %}
{%- for action in actions_written %}
{%- if action == "create" %}{% set m = "post" %}{% elif action == "update" %}{% set m = "patch" %}{% else %}{% set m = "delete" %}{% endif %}
        let res = server.{{ m }}(&route_table::{{ helper }}("globex", theirs)).json(&json!({})).await;
        assert_eq!(res.status_code(), 404, "{{ action }} in Globex");
{%- if parent_scoped %}
        let res = server.{{ m }}(&route_table::{{ helper }}("acme", theirs)).json(&json!({})).await;
        assert_eq!(res.status_code(), 404, "{{ action }} on Globex's {{ parent_label }} through Acme");
{%- endif %}
{%- endfor %}
    })
    .await;
}
{%- endif %}
{%- else %}
{%- if scoped and collection %}

/// `/acme/{{ file_name }}` (or one of its pages): one@ is the seeds' owner of Acme.
fn acme(page: &str) -> String {
    let index = route_table::{{ file_name }}_path("acme");
    if page.is_empty() {
        index
    } else {
        format!("{index}/{page}")
    }
}
{%- endif %}

#[tokio::test]
#[serial]
async fn signed_out_visitors_are_sent_to_sign_in() {
    with_app(|server, _ctx| async move {
{%- for page in pages %}
        assert_redirect(&server.get({% if scoped %}&acme("{% if page != "index" %}{{ page }}{% endif %}"){% else %}route_table::{{ upper }}{% if page != "index" %}_{{ page | upper_case }}{% endif %}{% endif %}).await, route_table::SIGN_IN);
{%- endfor %}
{%- if has_show %}
        assert_redirect(&server.get(&route_table::{{ singular }}_path({% if scoped %}"acme", {% endif %}{{ sample }})).await, route_table::SIGN_IN);
{%- endif %}
{%- if pages | length == 0 and not has_show %}
{%- for action in actions_written %}
{%- if action == "create" %}{% set m = "post" %}{% if scoped %}{% set at = `&acme("")` %}{% else %}{% set at = "route_table::" ~ upper %}{% endif %}
{%- else %}{% if action == "update" %}{% set m = "patch" %}{% else %}{% set m = "delete" %}{% endif %}{% if scoped %}{% set at = "&route_table::" ~ singular ~ `_path("acme", 1)` %}{% else %}{% set at = "&route_table::" ~ singular ~ "_path(1)" %}{% endif %}{% endif %}
        assert_redirect(&server.{{ m }}({{ at }}).json(&json!({})).await, route_table::SIGN_IN);
{%- endfor %}
{%- endif %}
    })
    .await;
}
{% for page in pages %}
#[tokio::test]
#[serial]
async fn {{ page }}_renders_its_page() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        let page = inertia_get(&server, &ctx, {% if scoped %}&acme("{% if page != "index" %}{{ page }}{% endif %}"){% else %}route_table::{{ upper }}{% if page != "index" %}_{{ page | upper_case }}{% endif %}{% endif %}).await;
        assert_eq!(page["component"], "{{ file_name }}/{{ page }}");
    })
    .await;
}
{% endfor -%}
{%- if has_show %}
#[tokio::test]
#[serial]
async fn show_renders_its_page() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        let page = inertia_get(&server, &ctx, &route_table::{{ singular }}_path({% if scoped %}"acme", {% endif %}{{ sample }})).await;
        assert_eq!(page["component"], "{{ file_name }}/show");
        assert_eq!(page["props"]["{{ show_param }}"], {{ sample }}{% if show_glob %}, "the glob keeps its slashes"{% endif %});
    })
    .await;
}
{% endif -%}
{%- if actions_written | length > 0 %}
#[tokio::test]
#[serial]
async fn write_actions_redirect_back_and_refuse_precognition() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
{%- for action in actions_written %}
{%- if action == "create" %}{% set m = "post" %}{% if scoped %}{% set at = `&acme("")` %}{% else %}{% set at = "route_table::" ~ upper %}{% endif %}
{%- else %}{% if action == "update" %}{% set m = "patch" %}{% else %}{% set m = "delete" %}{% endif %}{% if scoped %}{% set at = "&route_table::" ~ singular ~ `_path("acme", 1)` %}{% else %}{% set at = "&route_table::" ~ singular ~ "_path(1)" %}{% endif %}{% endif %}
        let res = server
            .{{ m }}({{ at }})
            .add_header("host", "localhost")
            .add_header("referer", "http://localhost/back-here")
            .json(&json!({}))
            .await;
        assert_redirect(&res, "/back-here");
        let res = server
            .{{ m }}({{ at }})
            .add_header("precognition", "true")
            .json(&json!({}))
            .await;
        assert_eq!(res.status_code(), 400, "{{ action }} refuses precognition");
{%- endfor %}
    })
    .await;
}
{%- endif %}
{%- if scoped %}

/// Members only: another account's pages{% if actions_written | length > 0 %} and actions{% endif %} are a 404.
#[tokio::test]
#[serial]
async fn a_non_member_gets_404() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await; // in Acme only
{%- if collection %}
        let globex = route_table::{{ file_name }}_path("globex");
{%- endif %}
{%- if "index" in pages %}
        assert_eq!(server.get(&globex).await.status_code(), 404);
{%- endif %}
{%- if has_show %}
        assert_eq!(server.get(&route_table::{{ singular }}_path("globex", {{ sample }})).await.status_code(), 404);
{%- endif %}
{%- for action in actions_written %}
{%- if action == "create" %}
        assert_eq!(server.post(&globex).json(&json!({})).await.status_code(), 404);
{%- elif action == "update" %}
        assert_eq!(server.patch(&route_table::{{ singular }}_path("globex", 1)).json(&json!({})).await.status_code(), 404);
{%- else %}
        assert_eq!(server.delete(&route_table::{{ singular }}_path("globex", 1)).await.status_code(), 404);
{%- endif %}
{%- endfor %}
    })
    .await;
}
{%- endif %}
{%- endif %}
