// Typelizer digest da69c65697674a4e3c3460a9e6668164
//
// DO NOT MODIFY: This file was automatically generated by `cargo loco task routes:generate` from src/route_table.rs.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** POST /:account_slug/invitations */
  create: (
    params: { accountSlug: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/:account_slug/invitations', params, options),
    method: 'post',
  }),

  /** DELETE /:account_slug/invitations/:id */
  destroy: (
    params: { accountSlug: string | number; id: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/:account_slug/invitations/:id', params, options),
    method: 'delete',
  }),
}
