//! Accounts: create, the overview page, settings, the switcher once prop, and where `/` and
//! sign-in land. Generated by `cargo loco generate scaffold accounts`, then rewritten for the
//! account scope (SPEC-C1).

use inertia_rust_starter_kit::{
    models::{accounts, memberships},
    route_table,
};
use sea_orm::{EntityTrait, PaginatorTrait};
use serde_json::json;
use serial_test::serial;

use super::*;

pub const TWO: &str = "two@example.com";

async fn count(ctx: &AppContext) -> u64 {
    accounts::Entity::find().count(&ctx.db).await.unwrap()
}

/// An Inertia GET that also sends the once-props the client already holds.
async fn inertia_get_except_once(
    server: &TestServer,
    ctx: &AppContext,
    path: &str,
    except_once: &str,
) -> Value {
    let res = server
        .get(path)
        .add_header("x-inertia", "true")
        .add_header("x-inertia-version", asset_version(ctx))
        .add_header("x-inertia-except-once-props", except_once.to_owned())
        .await;
    assert_eq!(res.status_code(), 200, "GET {path}: {}", res.text());
    res.json::<Value>()
}

#[tokio::test]
#[serial]
async fn signed_out_visitors_are_sent_to_sign_in() {
    with_app(|server, _ctx| async move {
        assert_redirect(
            &server.get(route_table::NEW_ACCOUNT).await,
            route_table::SIGN_IN,
        );
        assert_redirect(
            &server.get(&route_table::account_path("acme")).await,
            route_table::SIGN_IN,
        );
    })
    .await;
}

#[tokio::test]
#[serial]
async fn creating_an_account_makes_the_creator_its_owner() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        let page = inertia_get(&server, &ctx, route_table::NEW_ACCOUNT).await;
        assert_eq!(page["component"], "accounts/new");

        let res = server
            .post(route_table::ACCOUNTS)
            .json(&json!({ "name": "Initech" }))
            .await;
        assert_redirect(&res, "/initech");
        let account = accounts::Model::find_by_slug(&ctx.db, "initech")
            .await
            .unwrap();
        let one = user(&ctx, ONE).await;
        let membership = memberships::Model::find_for(&ctx.db, account.id, one.id)
            .await
            .unwrap();
        assert_eq!(membership.role, "owner");

        let page = inertia_get(&server, &ctx, "/initech").await;
        assert_eq!(page["flash"]["notice"], "Account created");
    })
    .await;
}

#[tokio::test]
#[serial]
async fn slugs_get_a_suffix_on_collision_and_for_reserved_paths() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        for (name, slug) in [
            ("Acme", "/acme-2"),
            ("ACME!", "/acme-3"),
            ("Settings", "/settings-2"),
            ("X", "/x-account"),
        ] {
            let res = server
                .post(route_table::ACCOUNTS)
                .json(&json!({ "name": name }))
                .await;
            assert_redirect(&res, slug);
        }
    })
    .await;
}

#[tokio::test]
#[serial]
async fn an_invalid_name_comes_back_as_errors() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        let before = count(&ctx).await;
        for (name, message) in [
            ("", "can't be blank"),
            (&*"x".repeat(61), "is too long (maximum is 60 characters)"),
        ] {
            let res = server
                .post(route_table::ACCOUNTS)
                .json(&json!({ "name": name }))
                .await;
            assert_redirect(&res, route_table::NEW_ACCOUNT);
            let page = inertia_get(&server, &ctx, route_table::NEW_ACCOUNT).await;
            assert_eq!(page["props"]["errors"], json!({ "name": [message] }));
        }
        assert_eq!(count(&ctx).await, before);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn the_overview_has_the_account_the_role_and_a_deferred_member_count() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, TWO).await;
        let page = inertia_get(&server, &ctx, "/acme").await;
        assert_eq!(page["component"], "accounts/show");
        assert_eq!(page["props"]["account"]["name"], "Acme");
        assert_eq!(page["props"]["account"]["slug"], "acme");
        assert_eq!(page["props"]["membership"], json!({ "role": "member" }));
        assert!(page["props"].get("members_count").is_none());
        assert_eq!(
            page["deferredProps"],
            json!({ "default": ["members_count"] })
        );

        let res = server
            .get("/acme")
            .add_header("x-inertia", "true")
            .add_header("x-inertia-version", asset_version(&ctx))
            .add_header("x-inertia-partial-component", "accounts/show")
            .add_header("x-inertia-partial-data", "members_count")
            .await;
        assert_eq!(res.json::<Value>()["props"]["members_count"], 2);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn settings_show_the_account_and_save_the_name_but_never_the_slug() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        let page = inertia_get(&server, &ctx, "/acme/settings").await;
        assert_eq!(page["component"], "accounts/settings");
        assert_eq!(page["props"]["account"]["name"], "Acme");

        let res = server
            .patch("/acme/settings")
            .json(&json!({ "name": "Acme Corp", "slug": "hacked" }))
            .await;
        assert_redirect(&res, "/acme/settings");
        let page = inertia_get(&server, &ctx, "/acme/settings").await;
        assert_eq!(page["flash"]["notice"], "Settings saved");
        assert_eq!(page["props"]["account"]["name"], "Acme Corp");
        assert_eq!(page["props"]["account"]["slug"], "acme");

        let res = server
            .patch("/acme/settings")
            .json(&json!({ "name": "" }))
            .await;
        assert_redirect(&res, "/acme/settings");
        let page = inertia_get(&server, &ctx, "/acme/settings").await;
        assert_eq!(
            page["props"]["errors"],
            json!({ "name": ["can't be blank"] })
        );
    })
    .await;
}

#[tokio::test]
#[serial]
async fn a_member_reads_settings_but_cannot_save_them() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, TWO).await;
        let page = inertia_get(&server, &ctx, "/acme/settings").await;
        assert_eq!(page["component"], "accounts/settings");
        let res = server
            .patch("/acme/settings")
            .json(&json!({ "name": "Hacked" }))
            .await;
        assert_redirect(&res, "/acme");
        let page = inertia_get(&server, &ctx, "/acme").await;
        assert_eq!(
            page["flash"]["alert"],
            "You don't have permission to do that"
        );
        let acme = accounts::Model::find_by_slug(&ctx.db, "acme")
            .await
            .unwrap();
        assert_eq!(acme.name, "Acme");
    })
    .await;
}

#[tokio::test]
#[serial]
async fn the_switcher_is_a_once_prop_resent_only_when_the_accounts_change() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, TWO).await;
        let page = inertia_get(&server, &ctx, "/acme").await;
        assert_eq!(
            page["props"]["accounts"],
            json!([{ "name": "Acme", "slug": "acme" }, { "name": "Globex", "slug": "globex" }])
        );
        let key = page["onceProps"]
            .as_object()
            .and_then(|m| m.keys().next().cloned())
            .expect("accounts is a once prop");
        assert!(key.starts_with("accounts:"), "{key}");
        assert_eq!(page["onceProps"][&key]["prop"], "accounts");

        // The client holds it: not sent again.
        let page = inertia_get_except_once(&server, &ctx, "/globex", &key).await;
        assert!(page["props"].get("accounts").is_none());

        // A new account changes the key, so the held list no longer matches.
        server
            .post(route_table::ACCOUNTS)
            .json(&json!({ "name": "Hooli" }))
            .await;
        let page = inertia_get_except_once(&server, &ctx, "/hooli", &key).await;
        assert_eq!(page["props"]["accounts"].as_array().unwrap().len(), 3);
        assert!(page["onceProps"].get(&key).is_none());
    })
    .await;
}

#[tokio::test]
#[serial]
async fn root_and_sign_in_go_to_the_last_used_account() {
    with_app(|mut server, ctx| async move {
        // Never visited one: the first account joined.
        let res = server
            .post(route_table::SIGN_IN)
            .json(&json!({ "email": TWO, "password": PASSWORD }))
            .await;
        assert_redirect(&res, "/acme");
        // Visiting an account makes it the last used one.
        inertia_get(&server, &ctx, "/globex").await;
        assert_eq!(user(&ctx, TWO).await.last_account_id, Some(2));
        assert_redirect(&server.get(route_table::ROOT).await, "/globex");
        sign_in(&mut server, &ctx, TWO).await;
        let res = server
            .post(route_table::SIGN_IN)
            .json(&json!({ "email": TWO, "password": PASSWORD }))
            .await;
        // Signed in already: the guest-only sign-in sends to `/`, which goes home.
        assert_redirect(&res, route_table::ROOT);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn a_user_with_no_accounts_goes_to_new_account() {
    with_sign_up(SignUp::Open, |mut server, ctx| async move {
        let res = server
            .post(route_table::SIGN_UP)
            .json(&json!({
                "name": "Loner",
                "email": "loner@example.com",
                "password": PASSWORD,
                "password_confirmation": PASSWORD,
            }))
            .await;
        assert_redirect(&res, "/loner-s-account");
        let loner = user(&ctx, "loner@example.com").await;
        let account = accounts::Model::find_by_slug(&ctx.db, "loner-s-account")
            .await
            .unwrap();
        let membership = memberships::Model::find_for(&ctx.db, account.id, loner.id)
            .await
            .unwrap();
        // Out of the account behind the model's back (its rules refuse the last owner).
        memberships::Entity::delete_by_id(membership.id)
            .exec(&ctx.db)
            .await
            .unwrap();
        sign_in(&mut server, &ctx, "loner@example.com").await;
        assert_redirect(
            &server.get(route_table::ROOT).await,
            route_table::NEW_ACCOUNT,
        );
    })
    .await;
}
