//! Invitations (SPEC-C1 "Tests"): inviting, the invitation page, accepting, and signing up
//! through one. Generated by `cargo loco generate controller invitations`, then rewritten.

use axum::http::StatusCode;
use inertia_rust_starter_kit::{
    models::{
        accounts,
        invitations::{self, SEED_TOKEN},
        memberships,
    },
    route_table,
};
use sea_orm::{ActiveModelTrait, ActiveValue, EntityTrait, PaginatorTrait, QueryFilter};
use serde_json::json;
use serial_test::serial;

use super::*;

const TWO: &str = "two@example.com";

fn invite(email: &str) -> Value {
    json!({ "email": email, "role": "member" })
}

async fn invitation_count(ctx: &AppContext) -> u64 {
    invitations::Entity::find().count(&ctx.db).await.unwrap()
}

/// The plain token from the delivered invitation mail.
fn token_from_mail(mail: &str) -> String {
    let body = decode_qp(mail);
    let start = body.find("/invitations/").expect("mail has the link") + "/invitations/".len();
    body[start..]
        .chars()
        .take_while(char::is_ascii_alphanumeric)
        .collect()
}

fn new_user(email: &str, invitation: &str) -> Value {
    json!({
        "name": "Three",
        "email": email,
        "password": PASSWORD,
        "password_confirmation": PASSWORD,
        "invitation": invitation,
    })
}

#[tokio::test]
#[serial]
async fn an_admin_invites_and_the_mail_is_enqueued_with_the_subject_and_link() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        let res = server
            .post("/acme/invitations")
            .json(&json!({ "email": "  New@Example.com ", "role": "admin" }))
            .await;
        assert_redirect(&res, "/acme/members");
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(
            page["flash"]["notice"],
            "Invitation sent to new@example.com"
        );

        let invitation = invitations::Entity::find()
            .filter(sea_orm::ColumnTrait::eq(
                &invitations::Column::Email,
                "new@example.com",
            ))
            .one(&ctx.db)
            .await
            .unwrap()
            .expect("normalized email stored");
        assert_eq!(invitation.role, "admin");
        assert_eq!(invitation.inviter_id, 1);
        let days =
            (invitation.expires_at.with_timezone(&chrono::Utc) - chrono::Utc::now()).num_hours();
        assert!(
            (167..=168).contains(&days),
            "expires in 7 days, got {days}h"
        );

        let mails = deliveries(&ctx);
        assert_eq!(mails.len(), 1);
        let mail = decode_qp(&mails[0]);
        assert!(mail.contains("To: new@example.com"), "{mail}");
        assert!(mail.contains("From: from@example.com"), "{mail}");
        assert!(
            mail.contains("Subject: Test User invited you to Acme on Inertia Rust Starter Kit"),
            "{mail}"
        );
        assert!(
            mail.contains("on Inertia Rust Starter Kit as an admin."),
            "{mail}"
        );
        let token = token_from_mail(&mails[0]);
        let link = format!("{}/invitations/{token}", settings(&ctx).base_url());
        assert!(mail.contains(&link), "{mail}");
        let expires_on = invitation.expires_at.format("%B %d, %Y").to_string();
        assert!(
            mail.contains(&format!("This invitation expires on {expires_on}.")),
            "{mail}"
        );

        // Stored hashed: the digest of the mailed token, never the token.
        let stored = invitations::Entity::find_by_id(invitation.id)
            .one(&ctx.db)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(stored.token_digest, invitations::digest(&token));
        assert_ne!(stored.token_digest, token);
        assert_eq!(stored.token_digest.len(), 64);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn duplicate_pending_and_already_a_member_are_errors() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        for (email, message) in [
            ("three@example.com", "has already been invited"),
            ("THREE@example.com", "has already been invited"),
            (TWO, "is already a member"),
            ("not-an-email", "is invalid"),
        ] {
            let res = server.post("/acme/invitations").json(&invite(email)).await;
            assert_redirect(&res, "/acme/members");
            let page = inertia_get(&server, &ctx, "/acme/members").await;
            assert_eq!(
                page["props"]["errors"],
                json!({ "email": [message] }),
                "{email}"
            );
        }
        let res = server
            .post("/acme/invitations")
            .json(&json!({ "email": "x@example.com", "role": "owner" }))
            .await;
        assert_redirect(&res, "/acme/members");
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(
            page["props"]["errors"],
            json!({ "role": ["is not included in the list"] })
        );
        assert_eq!(invitation_count(&ctx).await, 1);
        assert!(deliveries(&ctx).is_empty());
    })
    .await;
}

#[tokio::test]
#[serial]
async fn an_expired_invitation_does_not_block_a_new_one() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        travel(&ctx, chrono::Duration::days(8));
        let res = server
            .post("/acme/invitations")
            .json(&invite("three@example.com"))
            .await;
        assert_redirect(&res, "/acme/members");
        assert_eq!(invitation_count(&ctx).await, 2);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn precognition_validates_the_invite_without_writing_or_mailing() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        let res = server
            .post("/acme/invitations")
            .add_header("precognition", "true")
            .add_header("precognition-validate-only", "email")
            .json(&invite(TWO))
            .await;
        assert_eq!(res.status_code(), StatusCode::UNPROCESSABLE_ENTITY);
        assert_eq!(
            res.json::<Value>()["errors"],
            json!({ "email": ["is already a member"] })
        );
        let res = server
            .post("/acme/invitations")
            .add_header("precognition", "true")
            .json(&invite("fresh@example.com"))
            .await;
        assert_eq!(res.status_code(), StatusCode::NO_CONTENT);
        assert_eq!(invitation_count(&ctx).await, 1);
        assert!(deliveries(&ctx).is_empty());
    })
    .await;
}

#[tokio::test]
#[serial]
async fn an_admin_revokes_a_pending_invitation() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        let res = server.delete("/acme/invitations/1").await;
        assert_redirect(&res, "/acme/members");
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(page["flash"]["notice"], "Invitation revoked");
        assert_eq!(invitation_count(&ctx).await, 0);
        // Another account's invitation through Acme: 404.
        let res = server.delete("/acme/invitations/999").await;
        assert_eq!(res.status_code(), StatusCode::NOT_FOUND);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn the_invitation_page_for_a_signed_out_visitor() {
    with_app(|server, ctx| async move {
        let page = inertia_get(&server, &ctx, &format!("/invitations/{SEED_TOKEN}")).await;
        assert_eq!(page["component"], "invitations/show");
        assert_eq!(
            page["props"]
                .as_object()
                .unwrap()
                .iter()
                .filter(|(k, _)| !["errors", "auth"].contains(&k.as_str()))
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect::<serde_json::Map<_, _>>(),
            json!({
                "account_name": "Acme",
                "inviter_name": "Test User",
                "email": "three@example.com",
                "signed_in_as": null,
                "expired": false,
            })
            .as_object()
            .unwrap()
            .clone()
        );
        let res = server.get("/invitations/not-a-token").await;
        assert_eq!(res.status_code(), StatusCode::NOT_FOUND);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn an_expired_token_shows_expired_and_accept_is_refused() {
    with_sign_up(SignUp::Open, |mut server, ctx| async move {
        let three = sign_up(&mut server, "three@example.com", "").await;
        sign_in(&mut server, &ctx, &three).await;
        travel(&ctx, chrono::Duration::days(8));
        let path = format!("/invitations/{SEED_TOKEN}");
        let page = inertia_get(&server, &ctx, &path).await;
        assert_eq!(page["props"]["expired"], true);
        assert_eq!(page["props"]["signed_in_as"], "three@example.com");

        let res = server.post(&format!("{path}/accept")).await;
        assert_redirect(&res, &path);
        let page = inertia_get(&server, &ctx, &path).await;
        assert_eq!(page["flash"]["alert"], "This invitation has expired");
        assert!(
            memberships::Model::find_for(&ctx.db, 1, user(&ctx, &three).await.id)
                .await
                .is_err()
        );
    })
    .await;
}

#[tokio::test]
#[serial]
async fn an_accepted_token_shows_expired() {
    with_app(|mut server, ctx| async move {
        let mut seeded: invitations::ActiveModel = invitations::Entity::find_by_id(1)
            .one(&ctx.db)
            .await
            .unwrap()
            .unwrap()
            .into();
        seeded.accepted_at = ActiveValue::Set(Some(chrono::Utc::now().into()));
        seeded.update(&ctx.db).await.unwrap();
        sign_in(&mut server, &ctx, ONE).await;
        let page = inertia_get(&server, &ctx, &format!("/invitations/{SEED_TOKEN}")).await;
        assert_eq!(page["props"]["expired"], true);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn a_signed_in_user_with_another_email_is_refused() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, TWO).await;
        let path = format!("/invitations/{SEED_TOKEN}");
        let page = inertia_get(&server, &ctx, &path).await;
        assert_eq!(page["props"]["signed_in_as"], TWO);
        assert_eq!(page["props"]["email"], "three@example.com");
        let res = server.post(&format!("{path}/accept")).await;
        assert_redirect(&res, &path);
        let page = inertia_get(&server, &ctx, &path).await;
        assert_eq!(
            page["flash"]["alert"],
            "This invitation is for three@example.com"
        );
        let two = user(&ctx, TWO).await;
        assert_eq!(
            memberships::Model::find_for(&ctx.db, 1, two.id)
                .await
                .unwrap()
                .role,
            "member",
            "two keeps the member role it had, not the invitation's admin"
        );
    })
    .await;
}

#[tokio::test]
#[serial]
async fn the_invited_user_accepts_and_joins_with_the_invited_role() {
    with_sign_up(SignUp::Open, |mut server, ctx| async move {
        let three = sign_up(&mut server, "three@example.com", "").await;
        sign_in(&mut server, &ctx, &three).await;
        let path = format!("/invitations/{SEED_TOKEN}");
        let res = server.post(&format!("{path}/accept")).await;
        assert_redirect(&res, "/acme");
        let page = inertia_get(&server, &ctx, "/acme").await;
        assert_eq!(page["flash"]["notice"], "Welcome to Acme");
        assert_eq!(page["props"]["membership"]["role"], "admin");
        // Used once: now it shows as expired.
        let page = inertia_get(&server, &ctx, &path).await;
        assert_eq!(page["props"]["expired"], true);
    })
    .await;
}

/// Sign up `email` (through `invitation` when not empty) and return the email.
async fn sign_up(server: &mut TestServer, email: &str, invitation: &str) -> String {
    let res = server
        .post(route_table::SIGN_UP)
        .json(&new_user(email, invitation))
        .await;
    assert!(res.status_code().is_redirection(), "{}", res.text());
    // Sign out again, so the caller decides who is signed in.
    server.clear_cookies();
    email.to_owned()
}

#[tokio::test]
#[serial]
async fn sign_up_through_an_invitation_joins_without_a_personal_account_and_verified() {
    with_app(|server, ctx| async move {
        let accounts_before = accounts::Entity::find().count(&ctx.db).await.unwrap();
        let res = server
            .post(route_table::SIGN_UP)
            .json(&new_user("Three@Example.com", SEED_TOKEN))
            .await;
        assert_redirect(&res, "/acme");
        let page = inertia_get(&server, &ctx, "/acme").await;
        assert_eq!(page["flash"]["notice"], "Welcome to Acme");
        assert_eq!(page["props"]["membership"]["role"], "admin");
        assert_eq!(page["props"]["auth"]["user"]["verified"], true);
        assert_eq!(
            page["props"]["accounts"],
            json!([{ "name": "Acme", "slug": "acme" }])
        );
        assert_eq!(
            accounts::Entity::find().count(&ctx.db).await.unwrap(),
            accounts_before,
            "no personal account"
        );
        assert!(
            deliveries(&ctx).is_empty(),
            "no verification mail: the invitation proved the address"
        );
        let three = user(&ctx, "three@example.com").await;
        assert!(three.verified);
        let invitation = invitations::Entity::find_by_id(1)
            .one(&ctx.db)
            .await
            .unwrap()
            .unwrap();
        assert!(invitation.accepted_at.is_some());
    })
    .await;
}

#[tokio::test]
#[serial]
async fn sign_up_with_an_invitation_for_another_email_is_an_ordinary_sign_up() {
    with_sign_up(SignUp::Open, |server, ctx| async move {
        let res = server
            .post(route_table::SIGN_UP)
            .json(&new_user("someone@example.com", SEED_TOKEN))
            .await;
        assert_redirect(&res, "/three-s-account");
        let someone = user(&ctx, "someone@example.com").await;
        assert!(!someone.verified);
        assert!(memberships::Model::find_for(&ctx.db, 1, someone.id)
            .await
            .is_err());
        let invitation = invitations::Entity::find_by_id(1)
            .one(&ctx.db)
            .await
            .unwrap()
            .unwrap();
        assert!(invitation.accepted_at.is_none());
    })
    .await;
}

#[tokio::test]
#[serial]
async fn sign_up_without_an_invitation_creates_the_personal_account_as_owner() {
    with_sign_up(SignUp::Open, |server, ctx| async move {
        let res = server
            .post(route_table::SIGN_UP)
            .json(&json!({
                "name": "Ada Lovelace",
                "email": "ada@example.com",
                "password": PASSWORD,
                "password_confirmation": PASSWORD,
            }))
            .await;
        assert_redirect(&res, "/ada-lovelace-s-account");
        let account = accounts::Model::find_by_slug(&ctx.db, "ada-lovelace-s-account")
            .await
            .unwrap();
        assert_eq!(account.name, "Ada Lovelace's account");
        let ada = user(&ctx, "ada@example.com").await;
        let membership = memberships::Model::find_for(&ctx.db, account.id, ada.id)
            .await
            .unwrap();
        assert_eq!(membership.role, "owner");
        let page = inertia_get(&server, &ctx, "/ada-lovelace-s-account").await;
        assert_eq!(
            page["flash"]["notice"],
            "Welcome! You have signed up successfully"
        );
        assert!(deliveries(&ctx)[0].contains("Subject: Verify your email"));
    })
    .await;
}

#[tokio::test]
#[serial]
async fn sign_in_with_an_invitation_returns_to_it() {
    with_app(|mut server, _ctx| async move {
        let res = server
            .post(route_table::SIGN_IN)
            .json(&json!({ "email": TWO, "password": PASSWORD, "invitation": SEED_TOKEN }))
            .await;
        assert_redirect(&res, &format!("/invitations/{SEED_TOKEN}"));
        server.clear_cookies();
        let res = server
            .post(route_table::SIGN_IN)
            .json(&json!({ "email": TWO, "password": "wrong", "invitation": SEED_TOKEN }))
            .await;
        assert_redirect(&res, &format!("/sign_in?invitation={SEED_TOKEN}"));
    })
    .await;
}

#[tokio::test]
#[serial]
async fn a_blank_role_is_not_in_the_list() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        server
            .post("/acme/invitations")
            .json(&json!({ "email": "x@example.com", "role": "" }))
            .await;
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(
            page["props"]["errors"],
            json!({ "role": ["is not included in the list"] })
        );
    })
    .await;
}
