//! Scoping and roles (SPEC-C1 "Tests"): every `/{account_slug}/…` route answers a non-member
//! exactly like a missing account, 404; members can't manage; the last owner stays.
//! Generated by `cargo loco generate controller members`, then rewritten.

use axum::http::StatusCode;
use inertia_rust_starter_kit::{
    models::{accounts, invitations, memberships},
    route_table,
};
use sea_orm::{EntityTrait, PaginatorTrait};
use serde_json::json;
use serial_test::serial;

use super::*;

const TWO: &str = "two@example.com";
/// Seeds: membership ids. 1 = one in Acme (owner), 2 = two in Acme (member), 3 = two in Globex.
const TWO_IN_ACME: i64 = 2;
const TWO_IN_GLOBEX: i64 = 3;

async fn role_of(ctx: &AppContext, id: i64) -> Option<String> {
    memberships::Entity::find_by_id(id)
        .one(&ctx.db)
        .await
        .unwrap()
        .map(|m| m.role)
}

async fn send(server: &TestServer, method: &str, path: &str, body: Value) -> TestResponse {
    match method {
        "GET" => server.get(path).await,
        "POST" => server.post(path).json(&body).await,
        "PATCH" => server.patch(path).json(&body).await,
        "DELETE" => server.delete(path).await,
        _ => unreachable!(),
    }
}

/// Every account route, for `slug` and a membership id in it.
fn account_routes(slug: &str, member_id: i64) -> Vec<(&'static str, String, Value)> {
    vec![
        ("GET", format!("/{slug}"), json!({})),
        ("GET", format!("/{slug}/settings"), json!({})),
        (
            "PATCH",
            format!("/{slug}/settings"),
            json!({ "name": "Hacked" }),
        ),
        ("GET", format!("/{slug}/members"), json!({})),
        (
            "PATCH",
            format!("/{slug}/members/{member_id}"),
            json!({ "role": "member" }),
        ),
        ("DELETE", format!("/{slug}/members/{member_id}"), json!({})),
        (
            "POST",
            format!("/{slug}/invitations"),
            json!({ "email": "x@example.com", "role": "member" }),
        ),
        ("DELETE", format!("/{slug}/invitations/1"), json!({})),
    ]
}

#[tokio::test]
#[serial]
async fn a_non_member_gets_404_on_every_account_route_of_an_existing_account() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await; // in Acme only
        for (method, path, body) in account_routes("globex", TWO_IN_GLOBEX) {
            let res = send(&server, method, &path, body).await;
            assert_eq!(res.status_code(), StatusCode::NOT_FOUND, "{method} {path}");
        }
        // Nothing changed in Globex.
        let globex = accounts::Model::find_by_slug(&ctx.db, "globex")
            .await
            .unwrap();
        assert_eq!(globex.name, "Globex");
        assert_eq!(role_of(&ctx, TWO_IN_GLOBEX).await.as_deref(), Some("owner"));
        let invited = invitations::Entity::find().count(&ctx.db).await.unwrap();
        assert_eq!(invited, 1, "only the seeded invitation");
    })
    .await;
}

#[tokio::test]
#[serial]
async fn a_missing_account_is_the_same_404() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        for (method, path, body) in account_routes("nope", TWO_IN_GLOBEX) {
            let res = send(&server, method, &path, body).await;
            assert_eq!(res.status_code(), StatusCode::NOT_FOUND, "{method} {path}");
        }
        // The 404 for a real account is byte-for-byte the one for a missing one.
        let real = server.get("/globex").await;
        let missing = server.get("/nope").await;
        assert_eq!(real.text(), missing.text());
    })
    .await;
}

#[tokio::test]
#[serial]
async fn another_accounts_member_id_through_your_own_account_is_404() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await; // owner of Acme
        let res = server
            .patch(&format!("/acme/members/{TWO_IN_GLOBEX}"))
            .json(&json!({ "role": "member" }))
            .await;
        assert_eq!(res.status_code(), StatusCode::NOT_FOUND);
        let res = server
            .delete(&format!("/acme/members/{TWO_IN_GLOBEX}"))
            .await;
        assert_eq!(res.status_code(), StatusCode::NOT_FOUND);
        assert_eq!(role_of(&ctx, TWO_IN_GLOBEX).await.as_deref(), Some("owner"));
    })
    .await;
}

#[tokio::test]
#[serial]
async fn paths_that_are_not_slugs_still_reach_public_files() {
    with_app(|server, _ctx| async move {
        let res = server.get("/robots.txt").await;
        assert_eq!(res.status_code(), StatusCode::OK);
        let res = server.get("/icon.svg").await;
        assert_eq!(res.status_code(), StatusCode::OK);
    })
    .await;
}

/// Only a slug-shaped first segment reaches `/{account_slug}`; anything else is the ordinary 404
/// page, for a guest and for a signed-in user alike. (A slug-shaped path sends a guest to sign
/// in, like every signed-in page, and is the 404 above once signed in.)
#[tokio::test]
#[serial]
async fn junk_paths_that_cannot_be_slugs_are_the_404_page() {
    with_app(|mut server, ctx| async move {
        let not_found = std::fs::read_to_string("public/404.html").unwrap();
        let junk = [
            "/x.php",
            "/a/b/c",
            "/wp-admin/setup.php",
            "/A",
            "/ab",
            "/.env",
        ];
        for signed_in in [false, true] {
            if signed_in {
                sign_in(&mut server, &ctx, ONE).await;
            }
            for path in junk {
                let res = server.get(path).await;
                assert_eq!(
                    res.status_code(),
                    StatusCode::NOT_FOUND,
                    "{path} ({signed_in})"
                );
                assert_eq!(res.text(), not_found, "{path} ({signed_in})");
            }
        }
        // The same request for a slug-shaped path: a guest goes to sign in.
        server.clear_cookies();
        assert_redirect(&server.get("/nope").await, route_table::SIGN_IN);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn the_members_page_lists_members_and_for_managers_pending_invitations() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(page["component"], "members/index");
        assert_eq!(page["props"]["can_manage"], true);
        let members = page["props"]["members"].as_array().unwrap();
        assert_eq!(members.len(), 2);
        assert_eq!(members[0]["id"], 1);
        assert_eq!(
            members[0]["user"],
            json!({ "name": "Test User", "email": "one@example.com" })
        );
        assert_eq!(members[0]["role"], "owner");
        assert_eq!(members[0]["joined_at"], "2025-08-01T12:00:00.000Z");
        let invitations = page["props"]["invitations"].as_array().unwrap();
        assert_eq!(invitations.len(), 1);
        assert_eq!(invitations[0]["email"], "three@example.com");
        assert_eq!(invitations[0]["role"], "admin");
        assert_eq!(invitations[0]["inviter_name"], "Test User");
        assert!(invitations[0]["expires_at"]
            .as_str()
            .unwrap()
            .ends_with('Z'));

        sign_in(&mut server, &ctx, TWO).await;
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(page["props"]["can_manage"], false);
        assert_eq!(page["props"]["members"].as_array().unwrap().len(), 2);
        assert_eq!(page["props"]["invitations"], json!([]));
    })
    .await;
}

#[tokio::test]
#[serial]
async fn a_member_cannot_invite_change_roles_or_revoke() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, TWO).await; // member of Acme
        let attempts = [
            (
                "POST",
                "/acme/invitations".to_owned(),
                json!({ "email": "x@example.com", "role": "member" }),
            ),
            (
                "PATCH",
                "/acme/members/1".to_owned(),
                json!({ "role": "member" }),
            ),
            ("DELETE", "/acme/members/1".to_owned(), json!({})),
            ("DELETE", "/acme/invitations/1".to_owned(), json!({})),
        ];
        for (method, path, body) in attempts {
            let res = send(&server, method, &path, body).await;
            assert_redirect(&res, "/acme");
            let page = inertia_get(&server, &ctx, "/acme").await;
            assert_eq!(
                page["flash"]["alert"], "You don't have permission to do that",
                "{method} {path}"
            );
        }
        assert_eq!(role_of(&ctx, 1).await.as_deref(), Some("owner"));
        assert_eq!(invitations::Entity::find().count(&ctx.db).await.unwrap(), 1);
        // "Back" is the page the request came from, when it is on this site.
        let res = server
            .patch("/acme/members/1")
            .add_header("host", "localhost")
            .add_header("referer", "http://localhost/acme/members")
            .json(&json!({ "role": "member" }))
            .await;
        assert_redirect(&res, "/acme/members");
    })
    .await;
}

#[tokio::test]
#[serial]
async fn an_owner_changes_a_role() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await;
        let res = server
            .patch(&format!("/acme/members/{TWO_IN_ACME}"))
            .json(&json!({ "role": "admin" }))
            .await;
        assert_redirect(&res, "/acme/members");
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(page["flash"]["notice"], "Role updated");
        assert_eq!(role_of(&ctx, TWO_IN_ACME).await.as_deref(), Some("admin"));

        let res = server
            .patch(&format!("/acme/members/{TWO_IN_ACME}"))
            .json(&json!({ "role": "king" }))
            .await;
        assert_redirect(&res, "/acme/members");
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(page["flash"]["alert"], "Role is not included in the list");
    })
    .await;
}

#[tokio::test]
#[serial]
async fn the_last_owner_cannot_be_demoted_or_removed() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, ONE).await; // the only owner of Acme
        let res = server
            .patch("/acme/members/1")
            .json(&json!({ "role": "admin" }))
            .await;
        assert_redirect(&res, "/acme/members");
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(
            page["flash"]["alert"],
            "An account needs at least one owner"
        );
        assert_eq!(role_of(&ctx, 1).await.as_deref(), Some("owner"));

        let res = server.delete("/acme/members/1").await;
        assert_redirect(&res, "/acme/members");
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(
            page["flash"]["alert"],
            "An account needs at least one owner"
        );
        assert_eq!(role_of(&ctx, 1).await.as_deref(), Some("owner"));

        // With a second owner, the first can step down.
        server
            .patch(&format!("/acme/members/{TWO_IN_ACME}"))
            .json(&json!({ "role": "owner" }))
            .await;
        let res = server
            .patch("/acme/members/1")
            .json(&json!({ "role": "member" }))
            .await;
        assert_redirect(&res, "/acme/members");
        assert_eq!(role_of(&ctx, 1).await.as_deref(), Some("member"));
    })
    .await;
}

#[tokio::test]
#[serial]
async fn an_owner_removes_a_member_and_a_member_leaves() {
    with_app(|mut server, ctx| async move {
        sign_in(&mut server, &ctx, TWO).await;
        inertia_get(&server, &ctx, "/acme").await; // last used: Acme
        let res = server.delete(&format!("/acme/members/{TWO_IN_ACME}")).await;
        // Home is the last-used account if still a member, else the first joined: Globex.
        assert_redirect(&res, "/globex");
        let page = inertia_get(&server, &ctx, "/globex").await;
        assert_eq!(page["flash"]["notice"], "You left Acme");
        assert_eq!(role_of(&ctx, TWO_IN_ACME).await, None);
        assert_eq!(
            server.get("/acme").await.status_code(),
            StatusCode::NOT_FOUND
        );

        // An owner removes someone else.
        memberships::Model::find_or_create(&ctx.db, 1, 2, memberships::Role::Member)
            .await
            .unwrap();
        sign_in(&mut server, &ctx, ONE).await;
        let two = memberships::Model::find_for(&ctx.db, 1, 2).await.unwrap();
        let res = server.delete(&format!("/acme/members/{}", two.id)).await;
        assert_redirect(&res, "/acme/members");
        let page = inertia_get(&server, &ctx, "/acme/members").await;
        assert_eq!(page["flash"]["notice"], "Member removed");
    })
    .await;
}
