//! Delivers `InvitationMailer#invite` (Active Job's `deliver_later`). Generated by
//! `cargo loco generate worker invitation_delivery`; `perform` written by hand.
//!
//! The job holds only the invitation id. It mints the token when it runs and stores its
//! digest, so the plain token never sits in the queue table.

use loco_rs::{model::ModelError, prelude::*};
use serde::{Deserialize, Serialize};

use crate::{
    controllers::clock, mailers::invitation_mailer::InvitationMailer, models::invitations,
};

pub struct Worker {
    pub ctx: AppContext,
}

#[derive(Deserialize, Debug, Serialize)]
pub struct WorkerArgs {
    pub invitation_id: i64,
}

#[async_trait]
impl BackgroundWorker<WorkerArgs> for Worker {
    fn queue() -> Option<String> {
        Some("mailer".to_string())
    }

    fn build(ctx: &AppContext) -> Self {
        Self { ctx: ctx.clone() }
    }

    fn class_name() -> String {
        "InvitationDelivery".to_string()
    }

    /// Reload the invitation and mail it. One revoked, accepted or expired in the meantime is
    /// skipped, like Active Job discarding a job whose record is gone.
    async fn perform(&self, args: WorkerArgs) -> Result<()> {
        let details = match invitations::Model::find_details(&self.ctx.db, args.invitation_id).await
        {
            Ok(details) => details,
            Err(ModelError::EntityNotFound) => {
                tracing::info!(
                    invitation_id = args.invitation_id,
                    "invitation is gone; not sending"
                );
                return Ok(());
            }
            Err(err) => return Err(err.into()),
        };
        if !details.invitation.is_pending(clock(&self.ctx).now()) {
            tracing::info!(
                invitation_id = args.invitation_id,
                "invitation is no longer pending; not sending"
            );
            return Ok(());
        }
        let (invitation, token) = details.invitation.rotate_token(&self.ctx.db).await?;
        let details = invitations::Details {
            invitation,
            ..details
        };
        InvitationMailer::deliver_now(&self.ctx, &details, &token).await
    }
}
