//! Delivers [`UserMailer`] messages on the `mailer` queue (Active Job's `deliver_later`).
//! Generated by `cargo loco generate worker user_mailer_delivery`; `perform` written by hand.
//!
//! The job holds only who and which message. Nothing time-sensitive is queued, so a delayed
//! queue cannot deliver an already-expired link: the token is minted when the job runs.

use loco_rs::prelude::*;
use serde::{Deserialize, Serialize};

use crate::{
    mailers::user_mailer::UserMailer,
    models::{tokens::Purpose, users},
};

pub struct Worker {
    pub ctx: AppContext,
}

#[derive(Deserialize, Debug, Serialize)]
pub struct WorkerArgs {
    pub user_id: i64,
    pub purpose: Purpose,
}

#[async_trait]
impl BackgroundWorker<WorkerArgs> for Worker {
    fn queue() -> Option<String> {
        Some("mailer".to_string())
    }

    fn build(ctx: &AppContext) -> Self {
        Self { ctx: ctx.clone() }
    }

    /// The name jobs are queued under. Kept from before this job moved out of the mailer
    /// module, so jobs already in a queue when the app is upgraded still run.
    fn class_name() -> String {
        "UserMailerWorker".to_string()
    }

    /// Reloads the user (current email, current password digest) and mails it. A user
    /// deleted in the meantime is skipped, like Active Job discarding a job whose record
    /// no longer deserializes.
    async fn perform(&self, args: WorkerArgs) -> Result<()> {
        match users::Model::find_by_id(&self.ctx.db, args.user_id).await {
            Ok(user) => UserMailer::deliver_now(&self.ctx, &user, args.purpose).await,
            Err(ModelError::EntityNotFound) => {
                tracing::info!(
                    user_id = args.user_id,
                    purpose = args.purpose.as_str(),
                    "user is gone; not sending"
                );
                Ok(())
            }
            Err(err) => Err(err.into()),
        }
    }
}
