//! `InvitationMailer#invite`. Generated by `cargo loco generate mailer invitation_mailer`, then
//! written like `src/mailers/user_mailer.rs`: the request enqueues the invitation's id
//! ([`InvitationMailer::invite`]); the job ([`crate::workers::invitation_delivery`]) reloads it,
//! mints the token it mails and stores only that token's digest.
//!
//! Templates: `src/mailers/invitation_mailer/invite/{subject,html,text}.t`. `.t` files are not
//! autoescaped, so `html.t` escapes every user-controlled value.
#![allow(non_upper_case_globals)]

use loco_rs::prelude::*;
use serde_json::json;

use crate::{
    controllers::settings,
    models::{invitations, memberships::Role},
    route_table,
    workers::invitation_delivery::{Worker, WorkerArgs},
};

static invite: Dir<'_> = include_dir!("src/mailers/invitation_mailer/invite");

#[allow(clippy::module_name_repetitions)]
pub struct InvitationMailer {}
impl Mailer for InvitationMailer {}
impl InvitationMailer {
    /// `InvitationMailer.with(invitation:).invite.deliver_later`.
    ///
    /// # Errors
    /// Enqueueing failures (or, with `ForegroundBlocking` workers, delivery failures).
    pub async fn invite(ctx: &AppContext, invitation: &invitations::Model) -> Result<()> {
        Worker::perform_later(
            ctx,
            WorkerArgs {
                invitation_id: invitation.id,
            },
        )
        .await?;
        Ok(())
    }

    /// Render and send the invitation with `token` now (the job's half).
    ///
    /// # Errors
    /// Template rendering or delivery failures.
    pub async fn deliver_now(
        ctx: &AppContext,
        details: &invitations::Details,
        token: &str,
    ) -> Result<()> {
        let settings = settings(ctx)?;
        let invitation = &details.invitation;
        let role_phrase = match invitation.role() {
            Role::Admin => "an admin",
            Role::Owner | Role::Member => "a member",
        };
        Self::mail_template_now(
            ctx,
            &invite,
            mailer::Args {
                from: Some(settings.mail_from.clone()),
                to: invitation.email.clone(),
                locals: json!({
                    "inviter_name": details.inviter.name,
                    "account_name": details.account.name,
                    "role_phrase": role_phrase,
                    "app_name": settings.app_name,
                    "url": format!("{}{}", settings.base_url(), route_table::invitation_path(token)),
                    // Rails' `Date#to_fs(:long)`: "October 07, 2026".
                    "expires_on": invitation.expires_at.format("%B %d, %Y").to_string(),
                }),
                ..Default::default()
            },
        )
        .await
    }
}
