{#- `cargo loco generate channel <name>` (src/generate.rs renders this; Loco has no channel
    generator): the channel, registered in src/channels/mod.rs. See
    .claude/skills/starter-kit/recipes/live-updates.md. -#}
to: src/channels/{{ file_name }}.rs
skip_exists: true
message: "Channel `{{ channel }}` (src/channels/{{ file_name }}.rs) was added and registered in src/channels/mod.rs."
injections:
- into: src/channels/mod.rs
  after_last: "^pub mod \\w+;"
  content: "pub mod {{ file_name }};"
- into: src/channels/mod.rs
  before: "// channels-inject"
  content: "        Arc::new({{ file_name }}::{{ channel }}),"
---
//! `{{ channel }}` (Action Cable's `app/channels/{{ file_name }}_channel.rb`). Generated by
//! `cargo loco generate channel {{ file_name }}`.
//!
//! Clients subscribe with `{account: "<slug>", id: <id>}` (`useLiveReload("{{ channel }}", …)`
//! in `frontend/lib/live.ts`); members of that account are accepted and stream `id` within it.
//! Broadcast after a write commits:
//! `{{ channel }}::broadcast_to(record.account_id, record.id, json!({"type": "changed"}))`.

use loco_rs::prelude::*;
use serde::Serialize;
use serde_json::Value;

use crate::{
    auth::CurrentSession,
    live::{self, Channel, Subscription},
};

pub struct {{ channel }};

impl {{ channel }} {
    pub const NAME: &'static str = "{{ channel }}";

    /// `{{ channel }}.broadcast_to(record, payload)`: every accepted subscription to `id` in
    /// account `account_id` receives `payload`.
    pub fn broadcast_to(account_id: i64, id: impl std::fmt::Display, payload: impl Serialize) {
        live::broadcast_to(Self::NAME, Self::key(account_id, id), payload);
    }

    /// The stream key: the account is part of it, so a subscription accepted in one account
    /// never receives another account's broadcast for the same id.
    fn key(account_id: i64, id: impl std::fmt::Display) -> String {
        format!("{account_id}:{id}")
    }
}

#[async_trait]
impl Channel for {{ channel }} {
    fn name(&self) -> &'static str {
        Self::NAME
    }

    /// Who may subscribe, and to what. Members of the account in `params.account`, streaming
    /// `params.id` within that account. Once the record exists, look it up in the account here
    /// (`find_in_account`) so an id that isn't there is rejected rather than followed silently.
    async fn subscribed(
        &self,
        ctx: &AppContext,
        user: &CurrentSession,
        params: &Value,
    ) -> Result<Subscription> {
        let Some(membership) = super::membership(ctx, user, params).await else {
            return live::reject();
        };
        let Some(id) = params["id"].as_i64() else {
            return live::reject();
        };
        Ok(Subscription::stream_for(Self::key(membership.account_id, id)))
    }
}
