{#- The request test for `cargo loco generate channel <name>`. -#}
to: tests/requests/{{ file_name }}_channel.rs
skip_exists: true
message: "Its test (tests/requests/{{ file_name }}_channel.rs) was added. Run `cargo test --test mod requests::{{ file_name }}_channel`."
injections:
- into: tests/requests/mod.rs
  after_last: "^mod \\w+;"
  content: "mod {{ file_name }}_channel;"
---
//! `{{ channel }}`: who is accepted, and what they receive. Generated by
//! `cargo loco generate channel {{ file_name }}`; keep it in step with `subscribed`.

use std::time::Duration;

use futures_util::StreamExt;
use {{ pkg_name }}::{
    auth::CurrentSession,
    channels::{{ file_name }}::{{ channel }},
    live,
    models::sessions,
};
use serde_json::{json, Value};
use serial_test::serial;

use super::*;

async fn session_of(ctx: &AppContext, email: &str) -> CurrentSession {
    let user = user(ctx, email).await;
    let session =
        sessions::Model::create_for_user(&ctx.db, &user, &sessions::RequestDetails::default())
            .await
            .unwrap();
    CurrentSession { session, user }
}

/// The next frame of `stream` within half a second, if any.
async fn next(stream: &mut futures_util::stream::BoxStream<'static, Value>) -> Option<Value> {
    tokio::time::timeout(Duration::from_millis(500), stream.next())
        .await
        .ok()
        .flatten()
}

#[tokio::test]
#[serial]
async fn a_member_is_accepted_and_receives_broadcasts() {
    with_app(|_server, ctx| async move {
        let one = session_of(&ctx, ONE).await; // owner of Acme
        let id = live::identifier({{ channel }}::NAME, &json!({ "account": "acme", "id": 1 }));
        let mut stream = live::subscribe(&ctx, &one, vec![id.clone()]).await;
        assert_eq!(next(&mut stream).await.unwrap()["type"], "confirm_subscription");
        {{ channel }}::broadcast_to(1, 1, json!({ "type": "changed" }));
        let frame = next(&mut stream).await.expect("the broadcast");
        assert_eq!(frame["identifier"], id);
        assert_eq!(frame["message"], json!({ "type": "changed" }));
        // Another id's broadcast doesn't reach it.
        {{ channel }}::broadcast_to(1, 2, json!({ "type": "changed" }));
        assert_eq!(next(&mut stream).await, None);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn a_non_member_is_rejected_and_receives_nothing() {
    with_app(|_server, ctx| async move {
        let one = session_of(&ctx, ONE).await; // not in Globex
        let id = live::identifier({{ channel }}::NAME, &json!({ "account": "globex", "id": 1 }));
        let mut stream = live::subscribe(&ctx, &one, vec![id]).await;
        assert_eq!(next(&mut stream).await.unwrap()["type"], "reject_subscription");
        {{ channel }}::broadcast_to(2, 1, json!({ "type": "changed" }));
        assert_eq!(next(&mut stream).await, None);
    })
    .await;
}

#[tokio::test]
#[serial]
async fn the_same_id_in_another_account_is_not_received() {
    with_app(|_server, ctx| async move {
        let one = session_of(&ctx, ONE).await; // in Acme, not Globex
        // Accepted in Acme, asking for an id that belongs to Globex.
        let id = live::identifier({{ channel }}::NAME, &json!({ "account": "acme", "id": 7 }));
        let mut stream = live::subscribe(&ctx, &one, vec![id]).await;
        assert_eq!(next(&mut stream).await.unwrap()["type"], "confirm_subscription");
        {{ channel }}::broadcast_to(2, 7, json!({ "type": "changed" }));
        assert_eq!(next(&mut stream).await, None);
    })
    .await;
}
