// Typelizer digest 778daac355499edd3fd30196b490e491
//
// DO NOT MODIFY: This file was automatically generated by `cargo loco task routes:generate` from src/route_table.rs.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /accounts */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/accounts', {}, options),
    method: 'post',
  }),

  /** GET /accounts/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/accounts/new', {}, options),
    method: 'get',
  }),

  /** GET /:account_slug */
  show: (
    params: { accountSlug: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/:account_slug', params, options),
    method: 'get',
  }),

  /** GET /:account_slug/settings */
  edit: (
    params: { accountSlug: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/:account_slug/settings', params, options),
    method: 'get',
  }),

  /** PATCH /:account_slug/settings */
  update: (
    params: { accountSlug: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/:account_slug/settings', params, options),
    method: 'patch',
  }),
}
