// Typelizer digest d951aab25ec38bcdd3bfa10d0fe5a73e
//
// DO NOT MODIFY: This file was automatically generated by `cargo loco task routes:generate` from src/route_table.rs.
export { default as Routes } from './RoutesController'
export { default as accounts } from './AccountsController'
export { default as accountsInvitations } from './Accounts/InvitationsController'
export { default as dashboard } from './DashboardController'
export { default as home } from './HomeController'
export { default as identityEmailVerifications } from './Identity/EmailVerificationsController'
export { default as identityPasswordResets } from './Identity/PasswordResetsController'
export { default as invitations } from './InvitationsController'
export { default as members } from './MembersController'
export { default as sessions } from './SessionsController'
export { default as settingsEmails } from './Settings/EmailsController'
export { default as settingsPasswords } from './Settings/PasswordsController'
export { default as settingsProfiles } from './Settings/ProfilesController'
export { default as settingsSessions } from './Settings/SessionsController'
export { default as users } from './UsersController'

import _invitations from './InvitationsController'
import _accounts from './AccountsController'
import _accountsInvitations from './Accounts/InvitationsController'
import _members from './MembersController'
import _identityPasswordResets from './Identity/PasswordResetsController'
import _identityEmailVerifications from './Identity/EmailVerificationsController'
import _home from './HomeController'
import _sessions from './SessionsController'
import _Routes from './RoutesController'
import _settingsEmails from './Settings/EmailsController'
import _settingsPasswords from './Settings/PasswordsController'
import _settingsProfiles from './Settings/ProfilesController'
import _users from './UsersController'

export const acceptInvitation = _invitations.accept
export const account = _accounts.show
export const accountInvitation = _accountsInvitations.destroy
export const accountInvitations = _accountsInvitations.create
export const accountMember = _members.update
export const accountMembers = _members.index
export const accountSettings = _accounts.edit
export const editIdentityPasswordReset = _identityPasswordResets.edit
export const identityEmailVerification = _identityEmailVerifications.show
export const identityPasswordReset = _identityPasswordResets.update
export const invitation = _invitations.show
export const newAccount = _accounts.new
export const newIdentityPasswordReset = _identityPasswordResets.new
export const root = _home.index
export const session = _sessions.destroy
export const settingsAppearance = _Routes.settingsAppearance
export const settingsEmail = _settingsEmails.show
export const settingsPassword = _settingsPasswords.show
export const settingsProfile = _settingsProfiles.show
export const signIn = _sessions.new
export const signUp = _users.new
