// Typelizer digest 807a49f971875f2414993a9ab50c58b9
//
// DO NOT MODIFY: This file was automatically generated by `cargo loco task routes:generate` from src/route_table.rs.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /invitations/:token/accept */
  accept: (
    params: { token: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/invitations/:token/accept', params, options),
    method: 'post',
  }),

  /** GET /invitations/:token */
  show: (
    params: { token: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/invitations/:token', params, options),
    method: 'get',
  }),
}
