// Typelizer digest 206f47fe8b533998700736b90b1deb36
//
// DO NOT MODIFY: This file was automatically generated by `cargo loco task routes:generate` from src/route_table.rs.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /:account_slug/members */
  index: (
    params: { accountSlug: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/:account_slug/members', params, options),
    method: 'get',
  }),

  /** PATCH /:account_slug/members/:id */
  update: (
    params: { accountSlug: string | number; id: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/:account_slug/members/:id', params, options),
    method: 'patch',
  }),

  /** DELETE /:account_slug/members/:id */
  destroy: (
    params: { accountSlug: string | number; id: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/:account_slug/members/:id', params, options),
    method: 'delete',
  }),
}
